### PR TITLE
fix: [#1715] add search results info

### LINKED ISSUE #1715: DH - search results info - navigation enhancement
We want to improve the UX of the navigation by adding information about what has been searched and  enhancing the styling of the breadcrumbs. 

- [ ] add section "Your search results for:" and information about search query.

Image

- [ ] style breadcrumbs (18 px plus 2 colors)

Figma:
https://www.figma.com/design/mGO12IHXsIuWQUUHSJ5oZT/Navigation?node-id=9332-1941&t=TP8sPacGxYcfbnb9-1

### PR DESCRIPTION
**Pull request by sqrasdf**
closes #1715

### CODE REVIEW

File: ui/apps/ui/src/app/components/collections-navigation/collections-navigation.component.ts [hunk 1]
```diff
@@ -346,6 +346,13 @@ import { ConfigService } from '../../services/config.service';
       </div>
     </nav>
 
+    <div
+      class="container--xxl search-results-info"
+      *ngIf="(q$ | async) && (q$ | async) !== '*'"
+    >
+      Your search results for: “{{ q$ | async }}”
```
Comment (Michal-Kolomanski) [inline ui/apps/ui/src/app/components/collections-navigation/collections-navigation.component.ts]: Use the async pipe once with an ngIf alias
```
<div
  class="container--xxl search-results-info"
  *ngIf="(q$ | async) as query"
>
  <ng-container *ngIf="query && query !== '*'">
    Your search results for: “{{ query }}”
  </ng-container>
</div>
```

**Review by Michal-Kolomanski — COMMENTED** [review]
@agpul @agpul 
do we want to reflect capitalized letters here?

Image

Or maybe we should lowercase all of them always?

CANCER -> cancer
Cancer -> cancer

**Review by AlicjaSwierad — APPROVED** [review]

**Review by Michal-Kolomanski — APPROVED** [review]
👏
