### PR TITLE
fix: remove search suggestions duplicated groups

### LINKED ISSUE #242: Problem with Autocomplete from All catalogs
In All catalogs, there is always a duplicate of the category with the best match in the search results

image

### PR DESCRIPTION
**Pull request by danielkryska**
closes #242

image

### CODE REVIEW

File: ui/apps/ui/src/app/components/search-input/search-input.component.ts [hunk 1]
```diff
@@ -28,6 +28,7 @@ import { NavConfigsRepository } from '@collections/repositories/nav-configs.repo
 import { ICollectionNavConfig } from '@collections/repositories/types';
 import { DOCUMENT } from '@angular/common';
 import { RedirectService } from '@collections/services/redirect.service';
+import { LABEL } from '@collections/data/all/nav-config.data';
```
Comment (goreck888) [inline ui/apps/ui/src/app/components/search-input/search-input.component.ts:31]: I think you have unused import here, remove it.

**Review by goreck888 — APPROVED** [review]

**Review by Marcelinna — APPROVED** [review]
