### PR TITLE
fix: [#1653] fix displaying logo for adapters in all collection

### LINKED ISSUE #1653: Fix logo fetching for adapters in all collection
Adapters dont have logos in all collection

### PR DESCRIPTION
**Pull request by sqrasdf**
closes #1653

### CODE REVIEW

File: ui/apps/ui/src/app/collections/data/url-builder-utils.ts [hunk 1]
```diff
@@ -44,7 +44,12 @@ export const getEntityIdentifier = (entity: {
  * Builds marketplace URLs for different resource types
  */
 export const buildMarketplaceUrl = (
-  resourceType: 'services' | 'providers' | 'catalogues' | 'deployable_services',
+  resourceType:
+    | 'services'
+    | 'providers'
+    | 'catalogues'
+    | 'deployable_services'
+    | 'adapters',
```
Comment (Michal-Kolomanski) [inline ui/apps/ui/src/app/collections/data/url-builder-utils.ts]: this change is not necessary
